<script lang="ts">
	import { m } from '$lib/i18n/paraglide.js';
	import MemberPageHeader from '$lib/components/profile/MemberPageHeader.svelte';
	let { data } = $props();
	type Provider = typeof data.providers[number]; type Profile = typeof data.profiles[number];
	let providers = $state<Provider[]>(data.providers); let profiles = $state<Profile[]>(data.profiles); let error = $state(''); let notice = $state('');
	let providerName = $state(''); let providerType = $state<'OPENROUTER' | 'GOOGLE' | 'OPENAI_COMPATIBLE'>('OPENROUTER'); let apiKey = $state(''); let baseUrl = $state('');
	let profileName = $state(''); let modelId = $state(''); let providerId = $state('');
	async function api(path: string, method: string, body?: unknown) { const response = await fetch(path, { method, headers: body ? { 'Content-Type': 'application/json' } : undefined, body: body ? JSON.stringify(body) : undefined }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || m.ai_settings_error()); return payload; }
	async function addProvider() { error = ''; notice = ''; try { const body = await api('/api/ai/providers', 'POST', { name: providerName, type: providerType, apiKey, baseUrl }); providers = [body.provider, ...providers]; providerName = ''; apiKey = ''; baseUrl = ''; providerId ||= body.provider.id; notice = m.ai_settings_saved(); } catch (e) { error = e instanceof Error ? e.message : m.ai_settings_error(); } }
	async function addProfile() { error = ''; notice = ''; try { const body = await api('/api/ai/profiles', 'POST', { name: profileName, modelId, providerConfigId: providerId }); profiles = [body.profile, ...profiles]; profileName = ''; modelId = ''; notice = m.ai_settings_saved(); } catch (e) { error = e instanceof Error ? e.message : m.ai_settings_error(); } }
	async function setDefault(id: string) { try { const body = await api(`/api/ai/profiles/${id}`, 'PATCH', { isDefault: true }); profiles = profiles.map((profile) => ({ ...profile, isDefault: profile.id === body.profile.id })); } catch (e) { error = e instanceof Error ? e.message : m.ai_settings_error(); } }
	async function removeProvider(id: string) { try { await api(`/api/ai/providers/${id}`, 'DELETE'); providers = providers.filter((provider) => provider.id !== id); profiles = profiles.filter((profile) => profile.providerConfigId !== id); } catch (e) { error = e instanceof Error ? e.message : m.ai_settings_error(); } }
	async function removeProfile(id: string) { try { await api(`/api/ai/profiles/${id}`, 'DELETE'); profiles = profiles.filter((profile) => profile.id !== id); } catch (e) { error = e instanceof Error ? e.message : m.ai_settings_error(); } }
</script>
<svelte:head><title>{m.ai_settings_title()} | GL-Orbit</title><meta name="robots" content="noindex, nofollow" /></svelte:head>
<section class="grid gap-5 pb-24 pt-5 sm:pt-8"><MemberPageHeader title={m.ai_settings_title()} description={m.ai_settings_description()} headingId="ai-settings" />
	{#if error}<p class="rounded-xl border border-coral/30 bg-coral/10 p-3 text-sm text-coral-dark">{error}</p>{/if}{#if notice}<p class="rounded-xl bg-lavender/15 p-3 text-sm text-plum">{notice}</p>{/if}
	<div class="orbit-control p-5"><h2>{m.ai_provider_title()}</h2><form class="grid gap-3 mt-4" onsubmit={(event) => { event.preventDefault(); void addProvider(); }}><input bind:value={providerName} required maxlength="120" placeholder={m.ai_provider_name()} /><select bind:value={providerType}><option value="OPENROUTER">OpenRouter</option><option value="GOOGLE">Google Gemini</option><option value="OPENAI_COMPATIBLE">OpenAI-compatible</option></select>{#if providerType === 'OPENAI_COMPATIBLE'}<input bind:value={baseUrl} required type="url" placeholder={m.ai_provider_base_url()} />{/if}<input bind:value={apiKey} required type="password" autocomplete="off" placeholder={m.ai_provider_key()} /><button class="orbit-button" type="submit">{m.ai_provider_add()}</button></form>
		{#if providers.length === 0}<p class="muted">{m.ai_no_providers()}</p>{:else}<ul>{#each providers as provider (provider.id)}<li>{provider.name} · {provider.type}{#if provider.baseUrl} · {provider.baseUrl}{/if}<button type="button" onclick={() => removeProvider(provider.id)}>{m.ai_delete()}</button></li>{/each}</ul>{/if}</div>
	<div class="orbit-control p-5"><h2>{m.ai_model_title()}</h2><form class="grid gap-3 mt-4" onsubmit={(event) => { event.preventDefault(); void addProfile(); }}><select bind:value={providerId} required><option value="" disabled>{m.ai_provider_title()}</option>{#each providers as provider (provider.id)}<option value={provider.id}>{provider.name}</option>{/each}</select><input bind:value={profileName} required maxlength="120" placeholder={m.ai_model_name()} /><input bind:value={modelId} required maxlength="255" placeholder={m.ai_model_id()} /><button class="orbit-button" type="submit" disabled={!providers.length}>{m.ai_model_add()}</button></form>
		{#if profiles.length === 0}<p class="muted">{m.ai_no_models()}</p>{:else}<ul>{#each profiles as profile (profile.id)}<li><strong>{profile.name}</strong> · {profile.modelId} {#if profile.isDefault}<span>{m.ai_model_default()}</span>{:else}<button type="button" onclick={() => setDefault(profile.id)}>{m.ai_model_set_default()}</button>{/if}<button type="button" onclick={() => removeProfile(profile.id)}>{m.ai_delete()}</button></li>{/each}</ul>{/if}</div>
</section>
<style>h2 { font-family: var(--orbit-font-display); font-size: 1.2rem; } form input, form select { border: 1px solid var(--orbit-lavender); border-radius: .75rem; padding: .7rem; background: var(--orbit-paper); } li { display:flex; gap:.5rem; align-items:center; flex-wrap:wrap; padding:.65rem 0; border-bottom:1px solid color-mix(in srgb,var(--orbit-lavender) 25%,transparent); } li button { color:var(--orbit-coral-dark); font-size:.85rem; } .muted { color:var(--orbit-muted); margin-top:1rem; }</style>
