<script lang="ts">
	import { onMount } from 'svelte';
	import { adminFetch } from '$lib/admin/action-feedback.js';
	import ImageUpload from '$lib/components/admin/ImageUpload.svelte';

	type Item = { id: string; slug: string; titleTh: string; titleEn: string; contentTh: string; contentEn: string; coverImageUrl: string | null; sourceUrl: string | null; sourceName: string | null; publishedAt: string | null; status: 'DRAFT' | 'PUBLISHED' | 'ARCHIVED' };
	let items = $state<Item[]>([]); let loading = $state(true); let saving = $state(false); let editingId = $state<string | null>(null); let errorMessage = $state('');
	let form = $state({ slug: '', titleTh: '', titleEn: '', contentTh: '', contentEn: '', coverImageUrl: '', sourceUrl: '', sourceName: '', publishedAt: '', status: 'DRAFT' as Item['status'] });
	async function load() { loading = true; try { const res = await adminFetch('/api/admin/news?limit=100'); const body = await res.json(); if (!res.ok) throw new Error(body.error ?? 'โหลดข่าวไม่สำเร็จ'); items = body.data; } catch (error) { errorMessage = error instanceof Error ? error.message : 'โหลดข่าวไม่สำเร็จ'; } finally { loading = false; } }
	onMount(load);
	function reset() { editingId = null; errorMessage = ''; form = { slug: '', titleTh: '', titleEn: '', contentTh: '', contentEn: '', coverImageUrl: '', sourceUrl: '', sourceName: '', publishedAt: '', status: 'DRAFT' }; }
	async function edit(id: string) { const res = await adminFetch(`/api/admin/news/${id}`); const body = await res.json(); if (!res.ok) { errorMessage = body.error ?? 'โหลดข่าวไม่สำเร็จ'; return; } const item = body.data as Item; editingId = item.id; form = { slug: item.slug, titleTh: item.titleTh, titleEn: item.titleEn, contentTh: item.contentTh, contentEn: item.contentEn, coverImageUrl: item.coverImageUrl ?? '', sourceUrl: item.sourceUrl ?? '', sourceName: item.sourceName ?? '', publishedAt: item.publishedAt?.slice(0, 16) ?? '', status: item.status }; }
	async function save() { saving = true; errorMessage = ''; try { const res = await adminFetch(editingId ? `/api/admin/news/${editingId}` : '/api/admin/news', { method: editingId ? 'PUT' : 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ ...form, publishedAt: form.publishedAt ? new Date(form.publishedAt).toISOString() : null }) }); const body = await res.json(); if (!res.ok || !body.success) throw new Error(body.error ?? 'บันทึกไม่สำเร็จ'); reset(); await load(); } catch (error) { errorMessage = error instanceof Error ? error.message : 'บันทึกไม่สำเร็จ'; } finally { saving = false; } }
	async function remove(id: string) { if (!confirm('ลบข่าวนี้ใช่ไหม?')) return; const res = await adminFetch(`/api/admin/news/${id}`, { method: 'DELETE' }); if (!res.ok) { const body = await res.json(); errorMessage = body.error ?? 'ลบไม่สำเร็จ'; return; } await load(); }
</script>

<svelte:head><title>จัดการข่าว | GL-Orbit Admin</title></svelte:head>
<div class="space-y-6"><header class="flex items-end justify-between gap-4"><div><p class="text-sm font-semibold text-coral-dark">Admin</p><h1 class="text-3xl font-bold text-plum">จัดการข่าว</h1><p class="text-sm text-gray-500">ข่าวท้องถิ่นแสดงบนหน้า News & Events และหน้ารายละเอียด</p></div><button type="button" onclick={reset} class="rounded-xl bg-white px-4 py-2 text-sm font-semibold text-plum shadow-sm ring-1 ring-gray-200">สร้างข่าวใหม่</button></header>
{#if errorMessage}<p class="rounded-xl bg-red-50 p-3 text-sm text-red-700">{errorMessage}</p>{/if}
<section class="grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><form class="space-y-4 rounded-2xl bg-white p-5 shadow-sm ring-1 ring-gray-200" onsubmit={(event) => { event.preventDefault(); void save(); }}><h2 class="text-xl font-bold text-plum">{editingId ? 'แก้ไขข่าว' : 'เพิ่มข่าว'}</h2>
<label class="block text-sm font-medium">Slug<input bind:value={form.slug} class="mt-1 w-full rounded-xl border-gray-200 px-3 py-2" placeholder="my-news-story" /></label>
<div class="grid gap-4 sm:grid-cols-2"><label class="block text-sm font-medium">ชื่อข่าว (ไทย)<input bind:value={form.titleTh} class="mt-1 w-full rounded-xl border-gray-200 px-3 py-2" /></label><label class="block text-sm font-medium">Title (English)<input bind:value={form.titleEn} class="mt-1 w-full rounded-xl border-gray-200 px-3 py-2" /></label></div>
<div class="grid gap-4 sm:grid-cols-2"><label class="block text-sm font-medium">เนื้อหา (ไทย)<textarea bind:value={form.contentTh} rows="8" class="mt-1 w-full rounded-xl border-gray-200 px-3 py-2"></textarea></label><label class="block text-sm font-medium">Content (English)<textarea bind:value={form.contentEn} rows="8" class="mt-1 w-full rounded-xl border-gray-200 px-3 py-2"></textarea></label></div>
<ImageUpload bind:url={form.coverImageUrl} type="posters" purpose="news" label="ภาพปกข่าว (3:4)" />
<div class="grid gap-4 sm:grid-cols-2"><label class="block text-sm font-medium">Source URL<input bind:value={form.sourceUrl} type="url" class="mt-1 w-full rounded-xl border-gray-200 px-3 py-2" /></label><label class="block text-sm font-medium">ชื่อแหล่งที่มา<input bind:value={form.sourceName} class="mt-1 w-full rounded-xl border-gray-200 px-3 py-2" /></label></div>
<div class="grid gap-4 sm:grid-cols-2"><label class="block text-sm font-medium">สถานะ<select bind:value={form.status} class="mt-1 w-full rounded-xl border-gray-200 px-3 py-2"><option value="DRAFT">Draft</option><option value="PUBLISHED">Published</option><option value="ARCHIVED">Archived</option></select></label><label class="block text-sm font-medium">วันเผยแพร่<input bind:value={form.publishedAt} type="datetime-local" class="mt-1 w-full rounded-xl border-gray-200 px-3 py-2" /></label></div><div class="flex gap-3"><button disabled={saving} class="rounded-xl bg-coral px-4 py-2 text-sm font-semibold text-white disabled:opacity-60">{saving ? 'กำลังบันทึก...' : 'บันทึก'}</button>{#if editingId}<button type="button" onclick={reset} class="rounded-xl bg-gray-100 px-4 py-2 text-sm font-semibold">ยกเลิก</button>{/if}</div></form>
<section class="space-y-3 rounded-2xl bg-white p-5 shadow-sm ring-1 ring-gray-200"><h2 class="text-xl font-bold text-plum">รายการข่าว</h2>{#if loading}<p class="text-sm text-gray-500">กำลังโหลด...</p>{:else if !items.length}<p class="text-sm text-gray-500">ยังไม่มีข่าว</p>{:else}<div class="divide-y divide-gray-100">{#each items as item}<div class="flex items-start justify-between gap-3 py-3"><div><p class="font-semibold text-plum">{item.titleTh}</p><p class="text-xs text-gray-500">/{item.slug} · {item.status}</p></div><div class="flex gap-2"><button type="button" onclick={() => edit(item.id)} class="rounded-lg bg-gray-100 px-3 py-1.5 text-sm font-semibold">แก้ไข</button><button type="button" onclick={() => remove(item.id)} class="rounded-lg bg-red-50 px-3 py-1.5 text-sm font-semibold text-red-700">ลบ</button></div></div>{/each}</div>{/if}</section></section></div>
