<script lang="ts">
	import { onMount } from 'svelte';
	import { adminFetch } from '$lib/admin/action-feedback.js';
	type Report = { id: string; momentId: string; reason: string; details: string | null; status: string };
	let reports = $state<Report[]>([]); let loading = $state(true); let errorMessage = $state(''); let busyId = $state<string | null>(null);
	async function loadReports() { loading = true; try { const response = await adminFetch('/api/admin/moments/reports'); const result = await response.json(); if (!response.ok) throw new Error(result.message || 'โหลดรายการรายงานไม่สำเร็จ'); reports = result.reports ?? []; } catch (error) { errorMessage = error instanceof Error ? error.message : 'โหลดรายการรายงานไม่สำเร็จ'; } finally { loading = false; } }
	async function moderate(momentId: string, action: 'HIDE' | 'RESTORE' | 'DELETE' | 'DISMISS_REPORT') { busyId = momentId; try { const response = await adminFetch(`/api/admin/moments/${momentId}/moderate`, { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ action }) }); if (!response.ok) throw new Error((await response.json()).message || 'ดำเนินการไม่สำเร็จ'); await loadReports(); } catch (error) { errorMessage = error instanceof Error ? error.message : 'ดำเนินการไม่สำเร็จ'; } finally { busyId = null; } }
	onMount(loadReports);
</script>
<svelte:head><title>Moderate Moments | GL-Orbit Admin</title></svelte:head>
<div class="space-y-6"><header><p class="text-sm font-semibold text-coral-dark">Orbit Halo</p><h1 class="text-3xl font-bold text-plum">Moderate Moments</h1><p class="text-sm text-gray-500">ตรวจสอบรายงานและบันทึกการดำเนินการของผู้ดูแล</p></header>{#if errorMessage}<p class="rounded-xl bg-red-50 p-4 text-sm text-red-700">{errorMessage}</p>{/if}<section class="overflow-hidden rounded-2xl bg-white shadow-sm ring-1 ring-gray-200">{#if loading}<p class="p-5 text-sm text-gray-500">กำลังโหลด...</p>{:else if reports.length === 0}<p class="p-5 text-sm text-gray-500">ไม่มีรายการรายงาน</p>{:else}<div class="divide-y divide-gray-100">{#each reports as report}<article class="space-y-3 p-5"><div class="flex flex-wrap items-start justify-between gap-3"><div><p class="font-semibold text-plum">{report.reason}</p>{#if report.details}<p class="mt-1 text-sm text-gray-500">{report.details}</p>{/if}</div><span class="rounded-full bg-gray-100 px-3 py-1 text-xs font-semibold text-gray-600">{report.status}</span></div><div class="flex flex-wrap gap-2"><button disabled={busyId === report.momentId} onclick={() => moderate(report.momentId, 'HIDE')} class="rounded-lg bg-amber-50 px-3 py-1.5 text-sm font-semibold text-amber-800 disabled:opacity-60">ซ่อน</button><button disabled={busyId === report.momentId} onclick={() => moderate(report.momentId, 'RESTORE')} class="rounded-lg bg-mint/20 px-3 py-1.5 text-sm font-semibold text-mint-dark disabled:opacity-60">กู้คืน</button><button disabled={busyId === report.momentId} onclick={() => moderate(report.momentId, 'DISMISS_REPORT')} class="rounded-lg bg-gray-100 px-3 py-1.5 text-sm font-semibold text-gray-700 disabled:opacity-60">ปิดรายงาน</button><button disabled={busyId === report.momentId} onclick={() => moderate(report.momentId, 'DELETE')} class="rounded-lg bg-red-50 px-3 py-1.5 text-sm font-semibold text-red-700 disabled:opacity-60">ลบ</button></div></article>{/each}</div>{/if}</section></div>
